# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/designs/workbench.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Workbench(object):
    def setupUi(self, Workbench):
        Workbench.setObjectName("Workbench")
        Workbench.resize(1066, 742)
        self.gridLayout = QtWidgets.QGridLayout(Workbench)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(200, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.btn_run = QtWidgets.QPushButton(Workbench)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_run.sizePolicy().hasHeightForWidth())
        self.btn_run.setSizePolicy(sizePolicy)
        self.btn_run.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_run.setObjectName("btn_run")
        self.gridLayout.addWidget(self.btn_run, 5, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 564, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 2, 3, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 6, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Workbench)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 310, 671))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_add = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 4, 1)
        self.label = QtWidgets.QLabel(Workbench)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 6)
        self.btn_back = QtWidgets.QPushButton(Workbench)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 0, 0, 1, 1)
        self.btn_destination = QtWidgets.QPushButton(Workbench)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_destination.sizePolicy().hasHeightForWidth())
        self.btn_destination.setSizePolicy(sizePolicy)
        self.btn_destination.setBaseSize(QtCore.QSize(0, 0))
        self.btn_destination.setObjectName("btn_destination")
        self.gridLayout.addWidget(self.btn_destination, 3, 6, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 6, 1, 1)

        self.retranslateUi(Workbench)
        QtCore.QMetaObject.connectSlotsByName(Workbench)

    def retranslateUi(self, Workbench):
        _translate = QtCore.QCoreApplication.translate
        Workbench.setWindowTitle(_translate("Workbench", "Form"))
        self.btn_run.setText(_translate("Workbench", "Run"))
        self.btn_add.setText(_translate("Workbench", "Add"))
        self.btn_back.setText(_translate("Workbench", "back"))
        self.btn_destination.setText(_translate("Workbench", "Destination"))

